"""notes table

Revision ID: 408195c42ece
Revises: 
Create Date: 2020-07-06 16:40:45.018383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408195c42ece'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('folder', sa.String(length=100), nullable=True),
    sa.Column('contents', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('ts', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_folder'), 'notes', ['folder'], unique=False)
    op.create_index(op.f('ix_notes_userid'), 'notes', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_userid'), table_name='notes')
    op.drop_index(op.f('ix_notes_folder'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
